remote_theme: pages-themes/midnight@v0.2.0
layout: post
# Site settings
permalink: /:title/
markdown: GFM
paginate: 5
paginate_path: "/:num/"
date_format: "%Y-%m-%y"
plugins:
- jekyll-feed # creates an Atom feed for your site at /feed.xml.
- jekyll-paginate # enables pagination
- jekyll-seo-tag # adds search engine metadata to the site.
- jekyll-sitemap # creates a site map for your site at /sitemap.xml.
- jekyll-remote-theme # add this line to the plugins list if you already have one
